#!/usr/bin/bash

get_config() {
	REBASE_HELPER_CONFIG_FILE="${REBASE_HELPER_CONFIG_FILE:-/etc/ublue-os/rebase_helper.json}"
	QUERY="$1"
	FALLBACK="$2"
	shift
	shift
	OUTPUT="$(jq -r "$QUERY" "$REBASE_HELPER_CONFIG_FILE" 2>/dev/null || echo "$FALLBACK")"
	if [ "$OUTPUT" == "null" ] ; then
		echo "$FALLBACK"
		return
	fi
	echo "$OUTPUT"
}

IMAGE_BASE_NAME="$(get_config '."image-base-name"' "invalid-image-name")"

if [[ "$DX_HELPER_ENABLED" == 'false' || "$IMAGE_BASE_NAME" == "invalid-image-name" ]] ; then
  IMAGE_BASE_NAME="ferrium"
fi

rpm-ostree rebase ostree-image-signed:docker://ghcr.io/cappsyco/$IMAGE_BASE_NAME:latest
