name: Build ISOs
on:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name: [ferrium, ferrium-dx]
        fedora_version: [42]
    env:
      IMAGE_TAG: latest
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISOs
        uses: jasonn3/build-container-installer@v1.3.0
        id: build
        with:
          iso_name: ${{ matrix.image_name }}-${{ matrix.fedora_version }}.iso
          arch: x86_64
          image_name: ${{ matrix.image_name }}
          image_repo: ${{ env.IMAGE_REGISTRY }}
          variant: "cosmic"
          version: ${{ matrix.fedora_version }}
          image_tag: ${{ env.IMAGE_TAG }}
          secure_boot_key_url: "https://github.com/ublue-os/akmods/raw/main/certs/public_key.der"
          enrollment_password: "universalblue"

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
