name: generate-iso
on:
  workflow_dispatch:

jobs:
  iso:
    name: Create and Upload ISO
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image:
          - ferrium
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: iso
        with:
          arch: x86_64
          image_name: ${{ matrix.image }}
          image_repo: ghcr.io/winblues
          image_tag: latest
          version: 41
          iso_name: ${{ matrix.image }}-latest.iso
