name: Build Ferrium Base

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "06 03 * * *" # 03:06am UTC everyday
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    secrets: inherit
    with:
      image-name: ferrium
      dx: 0
