name: Build ISOs
on:
  workflow_dispatch:

jobs:
  iso:
    name: Create and Upload ISO
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - ferrium
          - ferrium-dx
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: iso
        with:
          arch: x86_64
          image_name: ${{ matrix.image }}
          image_repo: ghcr.io/cappsyco
          image_tag: latest
          version: 42
          iso_name: ${{ matrix.image }}-latest.iso
          variant: kinoite

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: ferrium
          image_repo: ghcr.io/cappsyco
          image_tag: latest
          version: 42
          variant: Server
          iso_name: ${{ env.IMAGE_NAME }}-${{ env.VERSION }}.iso

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
